### ISSUE TITLE
Do not use hardcoded destination directory

### ISSUE THREAD

**Issue by mkszuba** [aebrahim/pidgin-gnome-keyring#12]
Hello,

At the moment, running 'make install' places the plug-in in $DESTDIR/usr/lib/purple-2/. This will not work as expected in a lot of cases, for instance on amd64 machines running RedHat-compatible distros (in which case  the plug-in should go into /usr/lib64/purple-2/ - /usr/lib is for 32-bit libraries only). A much better way would be to simply ask libpurple, via pkg-config, where its plug-in directory is:

PLUGINDIR = $(pkg-config --variable=plugindir purple)
# ...

mkdir -p ${DESTDIR}/${PLUGINDIR}/
cp ${TARGET}.so ${DESTDIR}/${PLUGINDIR}/

**Comment by selurvedu** [comment]
:+1:
I personally install plugins into `~/.purple/plugins/` (only those which are not managed by my package manager).

**Comment by aebrahim** [comment]
You actually can do make install_local to install it there
