### ISSUE TITLE
Gnome purple keyring for Pidgin "cannot load collection:"

### ISSUE THREAD

**Issue by Cbhihe** [aebrahim/pidgin-gnome-keyring#15]
Hi, I am new to both pidgin and to the Gnome keyring, and so unsure that this is the right place to query about the following:
Running Gnome3 desktop on 4-13.5-1-ARCH (x86_64), I just installed 'pidgin', 'purple-plugin-pack', 'purple-skype-web', 'pidgin-lib-notify'... Also installed Purple Telegram, and '**purple-gnome-keyring 1.1-3**' from AUR.
All is well except that, everytime I launch pidgin, I get a small window with the foll0wong message: "_**Gnome Keyring Plugin could not load collection**_" with a close button. Can you give me pointers so I can troubleshoot this ? Or is it just me ? 
Any pointer will do so I can be on my way. Cheers. -ced

**Comment by bluca** [comment]
I think you are looking for this: https://github.com/GRBurst/purple-gnome-keyring

**Comment by Cbhihe** [comment]
Yes, done. Thank you and sorry for the bother.

**Comment by aebrahim** [comment]
closing
