### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by infinity0** [aebrahim/pidgin-gnome-keyring#5]
Hi, I'd be interested in packaging this software more "properly" for Debian, e.g. like [mozilla-gnome-keyring](https://packages.debian.org/sid/mozilla-gnome-keyring). This requires clarifying the license. I see that `make_package.py` mentions `gpl2` but could you explicitly state this in a `COPYING` file, and also clarify if you'd like to make it "GPL-2" or "GPL-2 or later"?

**Comment by aebrahim** [comment]
Thanks for the message.

The deb_copyright file has GPL v2 or later, which is what I'm using. I'll
make this clearer as you suggested.

**Comment by infinity0** [comment]
Ah, I was a bit hasty. It turns out that it is [already packaged](https://packages.debian.org/sid/pidgin-gnome-keyring). (This was done in the last few months.) And I overlooked the existence of the `deb_copyright` file. Everything is OK, you don't need to make any changes. Sorry for the noise!
